printWidth: 100                         # 超过最大值换行
tabWidth: 2                             # 缩进字节数
useTabs: false                          # 缩进不使用tab而是使用空格
semi: true                              # 句尾添加分号
singleQuote: true                       # 使用单引号代替双引号
jsxSingleQuote: true                    # JSX中使用单引号代替双引号
trailingComma: "es5"                    # 在对象或数组最后一个元素后面是否加逗号(在ES5中加尾逗号)
bracketSpacing: true                    # 数组括号与文字之间加空格，例如："{ foo: bar }"
jsxBracketSameLine: false               # JSX中把'>'单独放一行
arrowParens: "always"                   # 箭头函数参数只有一个时使用小括号
htmlWhitespaceSensitivity: "ignore"     # 忽略HTML中的空格
endOfLine: "lf"                         # 换行符统一采用\n